### ISSUE TITLE
Multiple filters

### ISSUE THREAD

**Issue by sebhahn** [kawabata/ox-pandoc#10]
Is it possible to define multiple filters e.g.

`#+PANDOC_OPTIONS: filter:~/.cabal/bin/pandoc-crossref`
`#+PANDOC_OPTIONS: filter:~/.cabal/bin/pandoc-citeproc`

in my case only the last one is considerd

**Comment by kawabata** [comment]
Any options defined in `org-pandoc-colon-separated-options' can be
defined multiple times by using ":" (colon).

e.g.
    #+PANDOC_OPTIONS: filter:~/filter-a:~/filter-b

regards,

**Comment by sebhahn** [comment]
I can confirm that this solution works! Thanks!
