### ISSUE TITLE
Definition of an abstract

### ISSUE THREAD

**Issue by sebhahn** [kawabata/ox-pandoc#11]
What is the best way to define/write an abstract

`#+PANDOC_METADATA: abstract:"This is my abstract"`

The method above doesn't seem to work.

**Comment by kawabata** [comment]
Could you try quoting _ENTIRE_ key-value pair?

e.g.

````
#+PANDOC_METADATA: "abstract:This is my abstract"
````
Regards,

**Comment by sebhahn** [comment]
this works thanks!
