### ISSUE TITLE
Referencing figures and tables

### ISSUE THREAD

**Issue by sebhahn** [kawabata/ox-pandoc#12]
I'm opening a new issues based on the question/problem mentioned https://github.com/kawabata/ox-pandoc/issues/8#issuecomment-153927118 and post it again:

Using the plain "pandoc" command I've found that

`#+CAPTION: insert figure caption here`
`#+NAME: fig:1`
`#+LABEL: fig:1`
`[[img.png]]`

does create

`\begin{figure}[htbp]`
`\centering`
`\includegraphics{img.png}`
`\caption{insert figure caption here}`
`\end{figure}`

and the reference `[@fig:1]` gets correctly translated to `fig.~\ref{fig:1}` (using pandoc-citeproc), but it doesn't work because `\label{fig:1}` is missing in the Latex output? Where is the problem org-mode or pandoc?

edit: exporting with standard org-mode export to latex gives:

`\caption{\label{fig:orgparagraph1} insert figure caption here}`

still not the right label, but at least it is in the latex code

**Comment by kawabata** [comment]
If this is a problem of plain pandoc command, then please consult it with pandoc developers.
`ox-pandoc' is a wrapper of "pandoc" command and usually does not interfere with contents 
of org-mode.

However, if you can't wait it, then probably assigning some preprocessor hooks,
something like using re-search-forward function to replace #+LABEL:** to \label{**} may
be helpful.

**Comment by sebhahn** [comment]
Ok I've posted the issue at the pandoc repo.

Thanks for the hint, but my Lisp skills are not very good :(

**Comment by kawabata** [comment]
Unfortunately, feeding following text does not prodcue useful latex output
in plain pandoc command, so my idea seems not operable.

I'm sorry for mentioning without confirmation.

````
#+CAPTION: insert figure caption here
#+NAME: fig:1
\label{fig:1}
[[img.png]]
````
