### ISSUE TITLE
PANDOC_VARIABLES aren't recognized

### ISSUE THREAD

**Issue by riwim** [kawabata/ox-pandoc#16]
Hi,

I'd like to provide pandoc with the information, that I want A4 as my papersize. On commandline I use:
`pandoc -V papersize:a4paper`
This works without problems.

Now I want to export my og-files in emacs with ox-pandoc. In ox-pandoc's README I found that I should use
`#+PANDOC_VARIABLES: papersize:a4paper`
in my org-file. But that doesn't work (PDF is still lettersize). Any ideas? Did I spell something wrong?

**Comment by tarleb** [comment]
Pandoc expects the `papersize` variable without the trailing *paper*.

    #+PANDOC_VARIABLES: papersize:a4

should work as intended.

A note for future versions of pandoc: the current pandoc development version now respects the `#+LaTeX_class_options` setting, so writing

    #+LATEX_CLASS_OPTIONS: [a4paper]

now works with org-native latex-exports as well as with exports via pandoc.
