### ISSUE TITLE
org -> latex: LaTex blocks are not considered

### ISSUE THREAD

**Issue by ag91** [kawabata/ox-pandoc#17]
Hello,

I am using this package, and it did such a good job so far, that I assumed the following issue belonged to pandoc (https://github.com/jgm/pandoc/issues/2915):

it seems that org LaTex blocks are omitted from the input file when pandoc is called.
So for the org:

```
* Hello
#+BEGIN_LaTeX
hi I am LaTex
#+END_LaTeX
```
I get a LaTex file such as:
```
...
\begin{document}
\maketitle



\end{document}
...
```
That happens only for LaTex blocks, as far as I know.
It would be great if this was solved.
By the way, this issue is a regression (if this is an ox-pandoc bug): some time ago it worked.

**Comment by ag91** [comment]
It seems a problem of org mode: also export to org buffer delete latex fragments.

**Comment by ag91** [comment]
It is a new feature of org mode: 
instead of the syntax
#+BEGIN_LaTex
we will use
#+BEGIN_export latex

**Comment by tarleb** [comment]
Corresponding PR for Pandoc: jgm/pandoc#2954
