### ISSUE TITLE
Properties drawer isn't recognized

### ISSUE THREAD

**Issue by mclearc** [kawabata/ox-pandoc#20]
In a [recent update](https://github.com/jgm/pandoc/issues/3095) to the org-reader pandoc now recognizes `UNNUMBERED` in the `PROPERTIES` attribute for headers. Running the latest development version of pandoc I can confirm this works via running pandoc on the command line. But it doesn't seem to work via export from org. Is there an easy fix for this? The `PROPERTIES` drawer has been recognized by pandoc since [pandoc 1.17.1](http://pandoc.org/releases.html#pandoc-1.17.1-4-jun-2016)

**Comment by tarleb** [comment]
My guess would be that the exporter doesn't find the development version of pandoc. Setting `org-pandoc-command` should help.  Place the below command somewhere in your `.emacs` or execute it directly with <kbd>M-:</kbd>

    ;; Assumes pandoc to be installed via `cabal`, replace with correct path to executable
    (setq org-pandoc-command (expand-file-name "~/.cabal/bin/pandoc"))

**Comment by mclearc** [comment]
That would have been my thought as well, but surprisingly it isn't the problem (or at least, it happens even with explicitly setting the org-pandoc-command as you've suggested).

**Comment by tarleb** [comment]
Sorry, I should have tried it first.  The true problem is that `:PROPERTIES:` drawers were lost in the intermediate org-export step.  This can be fixed by forcing `:PROPERTIES:` drawers to be exported via the `prop:t` export setting:

    #+OPTIONS: prop:t

**Comment by mclearc** [comment]
That did it – Thanks very much!
