### ISSUE TITLE
base64 encoding when producing html

### ISSUE THREAD

**Issue by jth005** [kawabata/ox-pandoc#21]
Hello, 

I'm wondering if it is possible to use ox-pandoc to base64 encode all images to an output html file. I want to do this so that I can share my html files without worrying if the images will load, and so my colleagues don't have to keep track of more than one file. 

RStudio can do this when an html is produced from an Rmarkdown file with Knitr, so I have a feeling that ox-pandoc can do this same. I tried to use 

> PANDOC_VARIABLES: --self-contained

but this wasn't what I was looking for.

**Comment by tarleb** [comment]
`#+PANDOC_VARIABLES` is for setting (meta) variables only.  Use `#+PANDOC_OPTIONS: self-contained:t` to get the images included as base64.

**Comment by jth005** [comment]
Thanks tarleb.
