### ISSUE TITLE
parse-raw has been removed as a valid option in pandoc 2.0

### ISSUE THREAD

**Issue by bdarcus** [kawabata/ox-pandoc#36]
As I'm using the latest repo version of pandoc, I can't get it to compile documents with ox-pandoc, given this change.

https://github.com/jgm/pandoc/commit/47a16065c44eb5028ca9b9e86993fe880ef2a37d

**Comment by kawabata** [comment]
It seems pandoc 2.0 has not yet released officialy, but if you don't want ="--parse-raw"= option,
would you try configure =org-pandoc-options= to remove =(parse-raw . t)= ?

**Comment by bdarcus** [comment]
Sorry; I never got around to this, as I reverted to pre-2.0, to avoid this.

Not sure if you've noticed, but pandoc 2.0 has been released now.

**Comment by kawabata** [comment]
I have updated 'ox-pandoc' to support pandoc 2.0.  I haven't extensively tested it yet, but it seems 2.0 is still  premature in some aspects....  If you find any problems, I'm glad if you let me know.

With best regards,
