### ISSUE TITLE
ox-pandoc doesn't correctly render bibliographic references if used with pandoc-zotxt

### ISSUE THREAD

**Issue by l-de-lellis** [kawabata/ox-pandoc#38]
Exporting a org-mode file to _odt_ or _html_ via ox-pandoc doesn't correctly render the bibliographic references inserted with pandoc-zotxt. In the org-mode file the filters are enabled by having "`#+PANDOC_OPTIONS: filter:pandoc-zotxt`" and "`#+PANDOC_OPTIONS: filter:pandoc-citeproc`" at the beginning of the file. 

In the output file there are "**(???)**" in place of the references.

Exporting on the command line via pandoc works as expected with the command "`pandoc -F pandoc-zotxt -F pandoc-citeproc my_fie.org -o my_file.odt`"

**Comment by kawabata** [comment]
Would you try specifying the option as follows?

"#+PANDOC_OPTIONS: filter:pandoc-zotxt:pandoc-citeproc"

Multiple options can only be specified by colon-separated list.

**Comment by l-de-lellis** [comment]
Works perfectly with the options specified as a colon-separated list. That was not clear to me, thanks for the help!
