### ISSUE TITLE
Warning (ox-pandoc): Pandoc command is not installed.

### ISSUE THREAD

**Issue by trenkert** [kawabata/ox-pandoc#4]
I have pandoc installed via cabal. 
~/.cabal/bin is in PATH. 
My pandoc command from terminal is "pandoc", "$ pandoc -h" works.
But when I start emacs, I get the message "Warning (ox-pandoc): Pandoc command is not installed."

What is causing this?

**Comment by kawabata** [comment]
Please make sure that in Emacs, '(executable-find "pandoc")' would properly find the correct path.
If not, please make sure that your value of "exec-path" variable properly reflects your PATH settings.

If you invoke Emacs from non-shell environment, it may not reflect PATH set by shell settings.
In such case, there are several tools that start interactive shell process within Emacs and then
reflect the value of PATH environment variable to "exec-path" variable of Emacs.

Regards...

**Comment by trenkert** [comment]
Thank you, I had to add (add-to-list 'exec-path "/home/user/.cabal/bin") to my init.el. Pandoc is now found by ox.pandoc. 

However, pandoc-citeproc is still not found, although it is installed:

pandoc: Filter pandoc-citeproc not found

**Comment by kawabata** [comment]
Emacs searches executables via 'exec-path' variable, but invoked executables
attempt to find other executables by an inherited "PATH" enviroment variable.

The best way to solve this complication is to synchronize value of Emacs 'exec-path'
variable and PATH environment variable, which are usually the same when Emacs is
invoked from shell, or use some other tools if not.  Simple way is to alter PATH variable
with 'setenv' function.

**Comment by arnabkdey** [comment]
I have a similar problem and the solution here somehow doesnt work. 

I use windows and have Pandoc 2.8 in C:/ProgramData/chocolatey/bin.

I have pointed this path in my PATH variable as well as using setenv and also tried  setting the 'exec-path to the path above. But when I try to export my org file to a docx, I still get the following message: Pandoc (version 1.12.4 or later) can not be found.
