### ISSUE TITLE
Symbol’s function definition is void: org-element-create

### ISSUE THREAD

**Issue by Qquanwei** [kawabata/ox-pandoc#54]
Environment:
  GNU Emacs 25.3.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.5) of 2018-01-12
  Org-mode version 9.1.13 (9.1.13-elpa @ /root/.emacs.d/elpa/org-20180730/)
  pandoc 1.12.4.2

Stage:
  IN org-file: `M-x org-pandoc-export-to-markdown`

**Comment by kawabata** [comment]
Hmm...
At leaset, ox-pandoc did not call this function by itself.
Quick googling indicates that it is defined in "org-element.el", so loading it
may solve the problem.
