### ISSUE TITLE
`filter` option cannot be repeated in ox-pandoc

### ISSUE THREAD

**Issue by egh** [kawabata/ox-pandoc#6]
Although pandoc allows the `--filter` option to be repeated, this does not work in `ox-pandoc`. If I customize `org-pandoc-options` to have multiple `filter` options, only the last one is used.

**Comment by kawabata** [comment]
Thank you for your report.

I think that I've fixed the problem.

Would you try the newest github version, by specifying multiple filters as
colon separated list?

i.e. if you want to specify both ~/a.py and ~/b.py as filters, then

#+PANDOC_OPTIONS: filter:~/a.py:~/b.py

and see if it works?

On Sat, Jul 4, 2015 at 3:01 AM, Erik Hetzner <notifications@github.com>
wrote:

> Although pandoc allows the --filter option to be repeated, this does not
> work in ox-pandoc. If I customize org-pandoc-options to have multiple
> filter options, only the last one is used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kawabata/ox-pandoc/issues/6>.
>



-- 
---------------------------------------------------------------------
川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by egh** [comment]
Thank you! That works, but I need to specify the complete file path. pandoc should search `$PATH` for the path to the filter. I think that perhaps `filter` should not be in `org-pandoc-file-options`.

Thank you also for `ox-pandoc`. It works perfectly and the code is wonderful. I am using it to export to Jekyll with all the advantages of pandoc.

**Comment by kawabata** [comment]
Thaks for your comment.
I've just removed 'filter' from 'org-pandoc-filter-options'.

**Comment by egh** [comment]
Thanks again!
