### ISSUE TITLE
google-chrome

### ISSUE THREAD

**Issue by OrionRandD** [kawabata/ox-pandoc#65]
How do I configure ox-pandoc to open html files - like reveal.js (export option -> pv) 
with firefox and not google-chrome as it seems to be the default?
Where do I tell ox-pandoc to use firefox in my emacs init.el?
thx a lot

**Comment by kawabata** [comment]
org-pandoc uses "org-open-file" function to open the file, so please read the DOCSTRING of the function or the source code of the function to understand or customize the way it opens the file.

Regards,
