### ISSUE TITLE
control where to render references

### ISSUE THREAD

**Issue by ringprince** [kawabata/ox-pandoc#68]
It would be great if it was possible to control where the references appear in the exported document.  pandoc supports this via the {#refs} div [pandoc site](https://pandoc.org/MANUAL.html#citations).  Would it be possible to support this in ox-pandoc

**Comment by tarleb** [comment]
This can be done by combining the solutions mentioned in jgm/pandoc#6262 and #51:

``` org
Text before

#+BEGIN_EXPORT org
,#+ATTR_HTML: :id refs
,#+BEGIN_refs
,#+END_refs
#+END_EXPORT

Text after
```

It's a bit verbose, but does the trick.

**Comment by ringprince** [comment]
Great!  This works perfectly. Many thanks for the extremely fast answer.  #impressed
