### ISSUE TITLE
Support for  Export Dispatcher

### ISSUE THREAD

**Issue by kepi** [kawabata/ox-pandoc#7]
Do you plan to "integrate" ox-pandoc with Org's Export Dispatcher? It would be great if we can export through same interface as we are used to.

**Comment by kawabata** [comment]
Once you've loaded the "ox-pandoc" library,
you can dispatch to pandoc expoter via C-c C-e (M-x org-export-dispatch).

You can configure the keyboard shortcut assignment via variable
'org-pandoc-menu-entry'.

On Thu, Aug 20, 2015 at 5:18 AM, Kepi <notifications@github.com> wrote:

> Do you plan to "integrate" ox-pandoc with Org's Export Dispatcher? It
> would be great if we can export through same interface as we are used to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kawabata/ox-pandoc/issues/7>.
>



-- 
---------------------------------------------------------------------
川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com

**Comment by kepi** [comment]
Sorry for this issue. I had ox-pandoc with deferred loading and because of that I didnt see it in dispatcher. Thanks @kawabata

**Comment by kawabata** [comment]
If you want ox-pandoc loading to be delayed while you want to use
export dispatcher feature, something like

(with-eval-after-load 'ox (require 'ox-pandoc))

would suffice.


On Fri, Aug 21, 2015 at 12:36 AM, Kepi <notifications@github.com> wrote:

> Sorry for this issue. I had ox-pandoc with deferred loading and because of
> that I didnt see it in dispatcher. Thanks @kawabata
> <https://github.com/kawabata>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kawabata/ox-pandoc/issues/7#issuecomment-133054224>.
>



-- 
---------------------------------------------------------------------
川幡 太一 (KAWABATA, Taichi) E-mail: kawabata.taichi@gmail.com
